# Default values for kms-generic-helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  postgresqlEnabled: true
  elasticsearchEnabled: true
  storageClass: ""

elasticsearch:
  security:
    elasticUsername: elastic

  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/elasticsearch
  metrics:
    image:
      repository: bitnamilegacy/elasticsearch-exporter
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  sysctlImage:
    repository: bitnamilegacy/os-shell

indexer:
  replicaCount: 1

  security:
    github_api_token: ""
    kaggle_username: ""
    kaggle_key: ""


  image:
    repository: qcdis/kb-indexer
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podLabels:
    app.kubernetes.io/component: indexer

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  persistence:
    enabled: false
    storageClass: ""
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    ## @param persistence.size Size for the PV
    ##
    size: 5Gi
    ## @param persistence.annotations Persistent Volume Claim annotations
    ##
    annotations: {}
    ## @param persistence.subPath The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services
    ##
    subPath: ""
    ## @param persistence.selector Selector to match an existing Persistent Volume for WordPress data PVC
    ## If set, the PVC can't have a PV dynamically provisioned for it
    ## E.g.
    ## selector:
    ##   matchLabels:
    ##     app: my-app
    ##
    selector: {}
    ## @param persistence.dataSource Custom PVC data source
    ##
    dataSource: {}

  service:
    type: ClusterIP
    port: 8001

kms_generic:
  postgresql:
    hostname: ""
    port: ""
    database: ""
    auth:
      username: ""
      password: ""
  base_path: "search"
  debug: false

  github_query_url: ""
  elasticsearch:
    url: ""

  security:
    kms_admin: ""
    kms_password: ""
    secret_key: ""
    allowed_hosts: "HOST[,OTHER_HOST]"
    csrf_trusted_origins: "https://HOST:PORT[,https://OTHER_HOST:PORT]"
  replicaCount: 1

  image:
    repository: qcdis/kms-generic
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podLabels:
    app.kubernetes.io/component: kms_generic

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
